---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
  name: edge-camera-streamer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: edge-camera-streamer
        version: v1
    spec:
      volumes:
      - hostPath:
          path: /dev/video0
        name: videosource
      containers:
      - image: gokulpch/webcam-streamer:v1
        imagePullPolicy: IfNotPresent
        name: edge-camera-streamer
        ports:
        - containerPort: 80
          name: flask
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/video0
          name: videosource
---

apiVersion: v1
kind: Service
metadata:
  name: edge-camera-streamer-svc
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    component: edge-camera-streamer
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
